import { byThreshold, defineRules, type Rule } from '../types';
import type { LineInput } from '../inputs';

const base: LineInput = {
  kv: 110,
  lengthKm: 30,
  loading: 0.4,
  n1Loading: 0.6,
  n1Cause: 'loss of a neighbouring circuit',
  mw: 50,
  tripped: false,
  conductorTempC: 25,
  designTempC: 50,
  clearanceMarginM: 2.5,
  windMs: 6,
  ambientC: 12,
  humidityPct: 80,
  hoursAbove90: 0,
  hoursN1Above100: 0,
  cable: false,
  loadingRampPerHour: 0,
  dlrHeadroom: 0.1,
  autoReclosesToday: 0,
  faults12m: 0,
  vegetationSurveyMonths: 10,
  lightningKm: 999,
  ageYears: 35,
  insulatorDefects: 0,
  towerCorrosionGrade: 2,
  thermographyHotspotC: 5,
  outageRequestsPending: 0,
  stale: false,
};
const ex = (p: Partial<LineInput>): LineInput => ({ ...base, ...p });

type R = Omit<Rule<LineInput>, 'assetType' | 'version' | 'condition'> & { version?: string; condition?: Rule<LineInput>['condition'] };
const rules = (list: R[]) =>
  defineRules<LineInput>(
    'line',
    list.map((r) => ({ version: '1.0.0', ...r, condition: r.condition ?? byThreshold(r.measure, r.threshold.op) })),
  );

export const lineRules = rules([
  // ------------------------------------------------------------------ base
  {
    id: 'LINE-B-001',
    maturity: 'base',
    severity: 'critical',
    description: 'Circuit loaded above its seasonal rating.',
    inputs: ['loading'],
    measure: (i) => i.loading * 100,
    threshold: { value: 100, unit: '%', source: 'Assumption', op: '>' },
    action: 'alarm',
    outcome: 'Overload alarm raised; coordinator asked for relief.',
    examples: { fires: [ex({ loading: 1.05 })], quiet: [ex({ loading: 0.95 })] },
  },
  {
    id: 'LINE-B-002',
    maturity: 'base',
    severity: 'warning',
    description: 'Circuit loaded above 90% of its seasonal rating.',
    inputs: ['loading'],
    measure: (i) => i.loading * 100,
    threshold: { value: 90, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'High loading published to neighbouring agents.',
    examples: { fires: [ex({ loading: 0.93 })], quiet: [ex({ loading: 0.85 })] },
  },
  {
    id: 'LINE-B-003',
    maturity: 'base',
    severity: 'warning',
    description: 'Circuit would exceed its rating after a single circuit outage elsewhere (N-1).',
    inputs: ['n1Loading', 'n1Cause'],
    measure: (i) => i.n1Loading * 100,
    threshold: { value: 100, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'N-1 exposure published; coordinator checks for preventive action.',
    examples: { fires: [ex({ n1Loading: 1.12 })], quiet: [ex({ n1Loading: 0.98 })] },
  },
  {
    id: 'LINE-B-004',
    maturity: 'base',
    severity: 'critical',
    description: 'Circuit out of service.',
    inputs: ['tripped'],
    measure: (i) => (i.tripped ? 1 : 0),
    threshold: { value: 1, unit: '', source: 'Synthetic', op: '>=' },
    action: 'alarm',
    outcome: 'Outage alarm; neighbouring circuits re-evaluated.',
    examples: { fires: [ex({ tripped: true })], quiet: [ex({ tripped: false })] },
  },
  {
    id: 'LINE-B-005',
    maturity: 'base',
    severity: 'critical',
    description: 'Conductor above its maximum design temperature.',
    reference: 'IEEE 738 heat balance (simplified)',
    inputs: ['conductorTempC', 'designTempC'],
    measure: (i) => i.conductorTempC - i.designTempC,
    threshold: { value: 0, unit: '°C over design', source: 'Assumption', op: '>' },
    action: 'alarm',
    outcome: 'Thermal alarm; ground clearance may be infringed.',
    examples: { fires: [ex({ conductorTempC: 55, designTempC: 50 })], quiet: [ex({ conductorTempC: 45, designTempC: 50 })] },
  },
  // ------------------------------------------------------------------ extended: loading and thermal
  {
    id: 'LINE-E-001',
    maturity: 'extended',
    severity: 'critical',
    description: 'Post-contingency loading above 120%: beyond what short-term ratings usually cover.',
    inputs: ['n1Loading', 'n1Cause'],
    measure: (i) => i.n1Loading * 100,
    threshold: { value: 120, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Preventive re-dispatch requested before the contingency happens.',
    examples: { fires: [ex({ n1Loading: 1.25 })], quiet: [ex({ n1Loading: 1.1 })] },
  },
  {
    id: 'LINE-E-002',
    maturity: 'extended',
    severity: 'warning',
    description: 'Conductor within 5 °C of its maximum design temperature.',
    inputs: ['conductorTempC', 'designTempC'],
    measure: (i) => i.designTempC - i.conductorTempC,
    threshold: { value: 5, unit: '°C below design', source: 'Assumption', op: '<' },
    action: 'publish',
    outcome: 'Thermal margin published; operators alerted.',
    examples: { fires: [ex({ conductorTempC: 47, designTempC: 50 })], quiet: [ex({ conductorTempC: 40, designTempC: 50 })] },
  },
  {
    id: 'LINE-E-003',
    maturity: 'extended',
    severity: 'critical',
    description: 'Ground clearance margin below 1 m at the present sag.',
    reference: 'Statutory clearance practice (illustrative margin)',
    inputs: ['clearanceMarginM', 'conductorTempC'],
    measure: (i) => i.clearanceMarginM,
    threshold: { value: 1, unit: 'm', source: 'Assumption', op: '<' },
    action: 'alarm',
    outcome: 'Clearance alarm; reduce loading on this circuit.',
    examples: { fires: [ex({ clearanceMarginM: 0.6 })], quiet: [ex({ clearanceMarginM: 1.5 })] },
  },
  {
    id: 'LINE-E-004',
    maturity: 'extended',
    severity: 'advisory',
    description: 'More than four hours above 90% loading today: accelerated conductor annealing risk.',
    inputs: ['hoursAbove90'],
    measure: (i) => i.hoursAbove90,
    threshold: { value: 4, unit: 'h', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Flagged for asset management review.',
    examples: { fires: [ex({ hoursAbove90: 5 })], quiet: [ex({ hoursAbove90: 2 })] },
  },
  {
    id: 'LINE-E-005',
    maturity: 'extended',
    severity: 'warning',
    description: 'Loading rising faster than 20% of rating per hour.',
    inputs: ['loadingRampPerHour', 'loading'],
    measure: (i) => i.loadingRampPerHour * 100,
    threshold: { value: 20, unit: '% per h', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Ramp published so the coordinator can act early.',
    examples: { fires: [ex({ loadingRampPerHour: 0.25 })], quiet: [ex({ loadingRampPerHour: 0.1 })] },
  },
  {
    id: 'LINE-E-006',
    maturity: 'extended',
    severity: 'info',
    description: 'Weather allows at least 15% more than the static rating (dynamic line rating).',
    reference: 'CIGRE TB 601 (dynamic rating principles)',
    inputs: ['dlrHeadroom', 'windMs', 'ambientC'],
    measure: (i) => i.dlrHeadroom * 100,
    threshold: { value: 15, unit: '%', source: 'Synthetic', op: '>=' },
    action: 'publish',
    outcome: 'Dynamic headroom published as an option for the coordinator; static rating still applies.',
    examples: { fires: [ex({ dlrHeadroom: 0.2 })], quiet: [ex({ dlrHeadroom: 0.05 })] },
  },
  {
    id: 'LINE-E-007',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Heavy loading in a hot, still spell: rating assumptions are at their weakest.',
    inputs: ['loading', 'windMs', 'ambientC'],
    measure: (i) => (i.windMs < 1.5 && i.ambientC > 22 ? i.loading * 100 : 0),
    threshold: { value: 80, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Advisory: consider reduced loading until the wind picks up.',
    examples: { fires: [ex({ loading: 0.85, windMs: 1, ambientC: 25 })], quiet: [ex({ loading: 0.85, windMs: 4, ambientC: 25 })] },
  },
  // ------------------------------------------------------------------ extended: weather
  {
    id: 'LINE-E-008',
    maturity: 'extended',
    severity: 'warning',
    description: 'Gale with the circuit loaded: conductor clashing and galloping risk.',
    inputs: ['windMs', 'loading'],
    measure: (i) => (i.loading > 0.6 ? i.windMs : 0),
    threshold: { value: 25, unit: 'm/s', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Weather risk published; storm protocol on standby.',
    examples: { fires: [ex({ windMs: 28, loading: 0.7 })], quiet: [ex({ windMs: 28, loading: 0.3 })] },
  },
  {
    id: 'LINE-E-009',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Icing conditions: near-freezing, humid and light wind.',
    inputs: ['ambientC', 'humidityPct', 'windMs'],
    measure: (i) => (i.ambientC > -3 && i.ambientC < 2 && i.windMs < 8 ? i.humidityPct : 0),
    threshold: { value: 90, unit: '% RH', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Icing advisory; ice loading increases sag.',
    examples: { fires: [ex({ ambientC: 0, humidityPct: 95, windMs: 3 })], quiet: [ex({ ambientC: 8, humidityPct: 95, windMs: 3 })] },
  },
  {
    id: 'LINE-E-010',
    maturity: 'extended',
    severity: 'warning',
    description: 'Lightning within 10 km of the route.',
    inputs: ['lightningKm'],
    measure: (i) => i.lightningKm,
    threshold: { value: 10, unit: 'km', source: 'Synthetic', op: '<' },
    action: 'publish',
    outcome: 'Trip risk published; auto-reclose watched.',
    examples: { fires: [ex({ lightningKm: 4 })], quiet: [ex({ lightningKm: 40 })] },
  },
  {
    id: 'LINE-E-011',
    maturity: 'extended',
    severity: 'warning',
    description: 'Two or more auto-recloses today: a persistent or recurring fault.',
    inputs: ['autoReclosesToday'],
    measure: (i) => i.autoReclosesToday,
    threshold: { value: 2, unit: 'operations', source: 'Synthetic', op: '>=' },
    action: 'publish',
    outcome: 'Patrol recommended to the field team.',
    examples: { fires: [ex({ autoReclosesToday: 2 })], quiet: [ex({ autoReclosesToday: 1 })] },
  },
  {
    id: 'LINE-E-012',
    maturity: 'extended',
    severity: 'advisory',
    description: 'More than three faults in the last 12 months.',
    inputs: ['faults12m'],
    measure: (i) => i.faults12m,
    threshold: { value: 3, unit: 'faults', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Reliability review flagged.',
    examples: { fires: [ex({ faults12m: 4 })], quiet: [ex({ faults12m: 2 })] },
  },
  // ------------------------------------------------------------------ extended: condition
  {
    id: 'LINE-E-013',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Vegetation survey older than 36 months.',
    inputs: ['vegetationSurveyMonths'],
    measure: (i) => i.vegetationSurveyMonths,
    threshold: { value: 36, unit: 'months', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Survey due; added to the maintenance plan.',
    examples: { fires: [ex({ vegetationSurveyMonths: 40 })], quiet: [ex({ vegetationSurveyMonths: 12 })] },
  },
  {
    id: 'LINE-E-014',
    maturity: 'extended',
    severity: 'warning',
    description: 'Vegetation survey overdue on a circuit loaded above 70%: sag brings trees into play.',
    inputs: ['vegetationSurveyMonths', 'loading'],
    measure: (i) => (i.vegetationSurveyMonths > 36 ? i.loading * 100 : 0),
    threshold: { value: 70, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Priority patrol recommended.',
    examples: { fires: [ex({ vegetationSurveyMonths: 40, loading: 0.8 })], quiet: [ex({ vegetationSurveyMonths: 40, loading: 0.5 })] },
  },
  {
    id: 'LINE-E-015',
    maturity: 'extended',
    severity: 'warning',
    description: 'Insulator defects recorded at the last survey.',
    inputs: ['insulatorDefects'],
    measure: (i) => i.insulatorDefects,
    threshold: { value: 1, unit: 'defects', source: 'Synthetic', op: '>=' },
    action: 'publish',
    outcome: 'Replacement work order proposed.',
    examples: { fires: [ex({ insulatorDefects: 2 })], quiet: [ex({ insulatorDefects: 0 })] },
  },
  {
    id: 'LINE-E-016',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Tower corrosion graded 4 or worse.',
    inputs: ['towerCorrosionGrade'],
    measure: (i) => i.towerCorrosionGrade,
    threshold: { value: 4, unit: 'grade (1 to 5)', source: 'Synthetic', op: '>=' },
    action: 'publish',
    outcome: 'Painting or member replacement planned.',
    examples: { fires: [ex({ towerCorrosionGrade: 4 })], quiet: [ex({ towerCorrosionGrade: 2 })] },
  },
  {
    id: 'LINE-E-017',
    maturity: 'extended',
    severity: 'warning',
    description: 'Joint hot spot more than 20 °C above the conductor at the last thermographic survey.',
    reference: 'Thermographic inspection practice (illustrative threshold)',
    inputs: ['thermographyHotspotC'],
    measure: (i) => i.thermographyHotspotC,
    threshold: { value: 20, unit: '°C rise', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Joint repair proposed; loading caution until repaired.',
    examples: { fires: [ex({ thermographyHotspotC: 28 })], quiet: [ex({ thermographyHotspotC: 8 })] },
  },
  {
    id: 'LINE-E-018',
    maturity: 'extended',
    severity: 'critical',
    description: 'Joint hot spot over 20 °C and the circuit above 80% load: risk of joint failure.',
    inputs: ['thermographyHotspotC', 'loading'],
    measure: (i) => (i.thermographyHotspotC > 20 ? i.loading * 100 : 0),
    threshold: { value: 80, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Load reduction requested until the joint is repaired.',
    examples: { fires: [ex({ thermographyHotspotC: 25, loading: 0.85 })], quiet: [ex({ thermographyHotspotC: 25, loading: 0.5 })] },
  },
  {
    id: 'LINE-E-019',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Circuit older than 50 years.',
    inputs: ['ageYears'],
    measure: (i) => i.ageYears,
    threshold: { value: 50, unit: 'years', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Included in the refurbishment programme review.',
    examples: { fires: [ex({ ageYears: 55 })], quiet: [ex({ ageYears: 30 })] },
  },
  {
    id: 'LINE-E-020',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Circuit older than 50 years carrying more than 80% of its rating.',
    inputs: ['ageYears', 'loading'],
    measure: (i) => (i.ageYears > 50 ? i.loading * 100 : 0),
    threshold: { value: 80, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Advisory: older conductor at high load; consider a survey.',
    examples: { fires: [ex({ ageYears: 55, loading: 0.85 })], quiet: [ex({ ageYears: 55, loading: 0.4 })] },
  },
  // ------------------------------------------------------------------ extended: operations
  {
    id: 'LINE-E-021',
    maturity: 'extended',
    severity: 'warning',
    description: 'Planned outage requested while the circuit carries an N-1 exposure above 90%.',
    inputs: ['outageRequestsPending', 'n1Loading'],
    measure: (i) => (i.outageRequestsPending > 0 ? i.n1Loading * 100 : 0),
    threshold: { value: 90, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Outage request flagged for rescheduling.',
    examples: { fires: [ex({ outageRequestsPending: 1, n1Loading: 0.95 })], quiet: [ex({ outageRequestsPending: 0, n1Loading: 0.95 })] },
  },
  {
    id: 'LINE-E-022',
    maturity: 'extended',
    severity: 'critical',
    description: 'Overloaded with the conductor above design temperature: act now.',
    inputs: ['loading', 'conductorTempC', 'designTempC'],
    measure: (i) => (i.conductorTempC > i.designTempC ? i.loading * 100 : 0),
    threshold: { value: 100, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Immediate re-dispatch or load reduction recommended.',
    examples: { fires: [ex({ loading: 1.1, conductorTempC: 60, designTempC: 50 })], quiet: [ex({ loading: 1.1, conductorTempC: 40 })] },
  },
  {
    id: 'LINE-E-023',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Loading below 5% for a circuit longer than 20 km: possible open point or data issue.',
    inputs: ['loading', 'lengthKm'],
    measure: (i) => (i.lengthKm > 20 && !i.tripped ? i.loading * 100 : 100),
    threshold: { value: 5, unit: '%', source: 'Assumption', op: '<' },
    action: 'publish',
    outcome: 'Configuration check requested.',
    examples: { fires: [ex({ loading: 0.02, lengthKm: 40 })], quiet: [ex({ loading: 0.3, lengthKm: 40 })] },
  },
  {
    id: 'LINE-E-024',
    maturity: 'extended',
    severity: 'warning',
    description: 'N-1 exposure above 100% for three hours or more today.',
    inputs: ['hoursN1Above100'],
    measure: (i) => i.hoursN1Above100,
    threshold: { value: 3, unit: 'h', source: 'Assumption', op: '>=' },
    action: 'publish',
    outcome: 'Recurring constraint logged for planning.',
    examples: { fires: [ex({ hoursN1Above100: 3.5 })], quiet: [ex({ hoursN1Above100: 1 })] },
  },
  {
    id: 'LINE-E-025',
    maturity: 'extended',
    severity: 'info',
    description: 'Telemetry stale: last known values held, conservative rating applied.',
    inputs: ['stale'],
    measure: (i) => (i.stale ? 1 : 0),
    threshold: { value: 1, unit: '', source: 'Synthetic', op: '>=' },
    action: 'localSafeMode',
    outcome: 'Agent applies the lowest seasonal rating less 10% until data returns.',
    examples: { fires: [ex({ stale: true })], quiet: [ex({ stale: false })] },
  },
  {
    id: 'LINE-E-026',
    maturity: 'extended',
    severity: 'warning',
    description: 'Stale telemetry on a circuit last seen above 80%.',
    inputs: ['stale', 'loading'],
    measure: (i) => (i.stale ? i.loading * 100 : 0),
    threshold: { value: 80, unit: '%', source: 'Assumption', op: '>' },
    action: 'localSafeMode',
    outcome: 'Local protection settings relied on; coordinator confidence reduced.',
    examples: { fires: [ex({ stale: true, loading: 0.9 })], quiet: [ex({ stale: true, loading: 0.4 })] },
  },
  {
    id: 'LINE-E-027',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Underground cable loaded above 85% (cables have long thermal time constants).',
    inputs: ['loading', 'cable'],
    measure: (i) => (i.cable ? i.loading * 100 : 0),
    threshold: { value: 85, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Cable thermal watch started.',
    examples: { fires: [ex({ loading: 0.9, cable: true })], quiet: [ex({ loading: 0.9, cable: false })] },
  },
  {
    id: 'LINE-E-028',
    maturity: 'extended',
    severity: 'warning',
    description: 'Wind above 20 m/s with the circuit carrying an N-1 exposure above 90%.',
    inputs: ['windMs', 'n1Loading'],
    measure: (i) => (i.windMs > 20 ? i.n1Loading * 100 : 0),
    threshold: { value: 90, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Pre-storm re-dispatch to restore N-1 security recommended.',
    examples: { fires: [ex({ windMs: 22, n1Loading: 0.95 })], quiet: [ex({ windMs: 10, n1Loading: 0.95 })] },
  },
  {
    id: 'LINE-E-029',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Clearance margin below 2 m: sag approaching design.',
    inputs: ['clearanceMarginM'],
    measure: (i) => i.clearanceMarginM,
    threshold: { value: 2, unit: 'm', source: 'Assumption', op: '<' },
    action: 'publish',
    outcome: 'Sag watch started.',
    examples: { fires: [ex({ clearanceMarginM: 1.5 })], quiet: [ex({ clearanceMarginM: 3 })] },
  },
  {
    id: 'LINE-E-030',
    maturity: 'extended',
    severity: 'info',
    description: 'Circuit carrying more than 300 MW: a principal corridor.',
    inputs: ['mw'],
    measure: (i) => Math.abs(i.mw),
    threshold: { value: 300, unit: 'MW', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Corridor flow published for situational awareness.',
    examples: { fires: [ex({ mw: 350 })], quiet: [ex({ mw: 120 })] },
  },
]);
