import { byThreshold, defineRules, type Rule } from '../types';
import type { TransformerInput } from '../inputs';
import { duval, duvalCode } from '../transformerModel';

const base: TransformerInput = {
  loading: 0.5,
  n1Loading: 0.7,
  units: 2,
  ambientC: 12,
  topOilC: 45,
  hotSpotC: 60,
  ageingRate: 0.02,
  ageingHoursToday: 1,
  h2: 30,
  ch4: 20,
  c2h2: 0.5,
  c2h4: 15,
  c2h6: 20,
  co: 300,
  co2: 3000,
  c2h2Rate: 0,
  h2Rate: 2,
  moisturePpm: 12,
  tapOps24h: 10,
  tapOpsSinceService: 40000,
  bushingTanDeltaPct: 0.4,
  bushingCapChangePct: 1,
  coolingFault: false,
  oilLevelPct: 95,
  buchholzAlarm: false,
  ageYears: 25,
  stale: false,
};
const ex = (p: Partial<TransformerInput>): TransformerInput => ({ ...base, ...p });

type R = Omit<Rule<TransformerInput>, 'assetType' | 'version' | 'condition'> & {
  version?: string;
  condition?: Rule<TransformerInput>['condition'];
};
const rules = (list: R[]) =>
  defineRules<TransformerInput>(
    'transformer',
    list.map((r) => ({ version: '1.0.0', ...r, condition: r.condition ?? byThreshold(r.measure, r.threshold.op) })),
  );

const IEC7 = 'IEC 60076-7 loading guide';
const IEC599 = 'IEC 60599 dissolved gas interpretation (typical values, indicative)';

export const transformerRules = rules([
  // ------------------------------------------------------------------ base
  {
    id: 'TX-B-001',
    maturity: 'base',
    severity: 'critical',
    description: 'Transformer group loaded above its rating.',
    inputs: ['loading'],
    measure: (i) => i.loading * 100,
    threshold: { value: 100, unit: '%', source: 'Assumption', op: '>' },
    action: 'alarm',
    outcome: 'Overload alarm; coordinator asked for relief.',
    examples: { fires: [ex({ loading: 1.08 })], quiet: [ex({ loading: 0.9 })] },
  },
  {
    id: 'TX-B-002',
    maturity: 'base',
    severity: 'warning',
    description: 'Remaining units would exceed their rating if one unit tripped (N-1).',
    inputs: ['n1Loading', 'units'],
    measure: (i) => i.n1Loading * 100,
    threshold: { value: 100, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Firm capacity exceeded; published to the coordinator.',
    examples: { fires: [ex({ n1Loading: 1.1 })], quiet: [ex({ n1Loading: 0.9 })] },
  },
  {
    id: 'TX-B-003',
    maturity: 'base',
    severity: 'warning',
    description: 'Top-oil temperature above 95 °C.',
    reference: IEC7,
    inputs: ['topOilC'],
    measure: (i) => i.topOilC,
    threshold: { value: 95, unit: '°C', source: 'Assumption', op: '>' },
    action: 'alarm',
    outcome: 'Thermal alarm; cooling checked.',
    examples: { fires: [ex({ topOilC: 98 })], quiet: [ex({ topOilC: 70 })] },
  },
  {
    id: 'TX-B-004',
    maturity: 'base',
    severity: 'critical',
    description: 'Buchholz relay alarm.',
    inputs: ['buchholzAlarm'],
    measure: (i) => (i.buchholzAlarm ? 1 : 0),
    threshold: { value: 1, unit: '', source: 'Synthetic', op: '>=' },
    action: 'alarm',
    outcome: 'Gas accumulation alarm; unit to be taken out for investigation.',
    examples: { fires: [ex({ buchholzAlarm: true })], quiet: [ex({})] },
  },
  {
    id: 'TX-B-005',
    maturity: 'base',
    severity: 'warning',
    description: 'Oil level below 80%.',
    inputs: ['oilLevelPct'],
    measure: (i) => i.oilLevelPct,
    threshold: { value: 80, unit: '%', source: 'Synthetic', op: '<' },
    action: 'alarm',
    outcome: 'Leak check requested.',
    examples: { fires: [ex({ oilLevelPct: 70 })], quiet: [ex({ oilLevelPct: 95 })] },
  },
  // ------------------------------------------------------------------ extended: thermal
  {
    id: 'TX-E-001',
    maturity: 'extended',
    severity: 'warning',
    description: 'Winding hot spot above 110 °C (normal cyclic loading limit).',
    reference: IEC7,
    inputs: ['hotSpotC', 'loading', 'ambientC'],
    measure: (i) => i.hotSpotC,
    threshold: { value: 110, unit: '°C', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Loading caution published; ageing accelerated.',
    examples: { fires: [ex({ hotSpotC: 115 })], quiet: [ex({ hotSpotC: 90 })] },
  },
  {
    id: 'TX-E-002',
    maturity: 'extended',
    severity: 'critical',
    description: 'Winding hot spot above 140 °C (long-time emergency limit).',
    reference: IEC7,
    inputs: ['hotSpotC'],
    measure: (i) => i.hotSpotC,
    threshold: { value: 140, unit: '°C', source: 'Public', op: '>' },
    action: 'recommend',
    outcome: 'Immediate load reduction recommended.',
    examples: { fires: [ex({ hotSpotC: 145 })], quiet: [ex({ hotSpotC: 120 })] },
  },
  {
    id: 'TX-E-003',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Relative ageing rate above 2: insulation life consumed twice as fast as at 98 °C.',
    reference: IEC7,
    inputs: ['ageingRate', 'hotSpotC'],
    measure: (i) => i.ageingRate,
    threshold: { value: 2, unit: 'x', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Ageing logged for asset management.',
    examples: { fires: [ex({ ageingRate: 3 })], quiet: [ex({ ageingRate: 0.5 })] },
  },
  {
    id: 'TX-E-004',
    maturity: 'extended',
    severity: 'warning',
    description: 'More than 24 equivalent ageing hours accumulated today.',
    reference: IEC7,
    inputs: ['ageingHoursToday'],
    measure: (i) => i.ageingHoursToday,
    threshold: { value: 24, unit: 'h', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Daily ageing budget exceeded.',
    examples: { fires: [ex({ ageingHoursToday: 30 })], quiet: [ex({ ageingHoursToday: 6 })] },
  },
  {
    id: 'TX-E-005',
    maturity: 'extended',
    severity: 'warning',
    description: 'Cooling fault with the unit loaded above 70%.',
    inputs: ['coolingFault', 'loading'],
    measure: (i) => (i.coolingFault ? i.loading * 100 : 0),
    threshold: { value: 70, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Load transfer to other units recommended until cooling is restored.',
    examples: { fires: [ex({ coolingFault: true, loading: 0.8 })], quiet: [ex({ coolingFault: true, loading: 0.4 })] },
  },
  {
    id: 'TX-E-006',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Cooling fault recorded.',
    inputs: ['coolingFault'],
    measure: (i) => (i.coolingFault ? 1 : 0),
    threshold: { value: 1, unit: '', source: 'Synthetic', op: '>=' },
    action: 'publish',
    outcome: 'Maintenance call raised.',
    examples: { fires: [ex({ coolingFault: true })], quiet: [ex({})] },
  },
  {
    id: 'TX-E-007',
    maturity: 'extended',
    severity: 'advisory',
    description: 'N-1 loading above 90% of firm capacity.',
    inputs: ['n1Loading'],
    measure: (i) => i.n1Loading * 100,
    threshold: { value: 90, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Firm capacity watch started.',
    examples: { fires: [ex({ n1Loading: 0.95 })], quiet: [ex({ n1Loading: 0.7 })] },
  },
  // ------------------------------------------------------------------ extended: dissolved gas
  {
    id: 'TX-E-008',
    maturity: 'extended',
    severity: 'critical',
    description: 'Duval triangle indicates an electrical discharge (D1 or D2).',
    reference: `${IEC599}; Duval triangle 1`,
    inputs: ['ch4', 'c2h4', 'c2h2'],
    measure: (i) => duvalCode[duval(i.ch4, i.c2h4, i.c2h2)],
    threshold: { value: 6, unit: 'zone code (6 = D1, 7 = D2)', source: 'Public', op: '>=' },
    condition: (i, t) => i.c2h2 >= 1 && duvalCode[duval(i.ch4, i.c2h4, i.c2h2)] >= t,
    action: 'recommend',
    outcome: 'Oil resample within 7 days and loading restriction recommended.',
    examples: { fires: [ex({ ch4: 10, c2h4: 8, c2h2: 6 })], quiet: [ex({ ch4: 20, c2h4: 15, c2h2: 0.5 })] },
  },
  {
    id: 'TX-E-009',
    maturity: 'extended',
    severity: 'warning',
    description: 'Duval triangle indicates a high-temperature thermal fault (T3).',
    reference: `${IEC599}; Duval triangle 1`,
    inputs: ['ch4', 'c2h4', 'c2h2'],
    measure: (i) => duvalCode[duval(i.ch4, i.c2h4, i.c2h2)],
    threshold: { value: 4, unit: 'zone code (4 = T3)', source: 'Public', op: '=' },
    condition: (i, t) => i.c2h4 >= 50 && duvalCode[duval(i.ch4, i.c2h4, i.c2h2)] === t,
    action: 'recommend',
    outcome: 'Oil resample and thermographic survey recommended.',
    examples: { fires: [ex({ ch4: 40, c2h4: 120, c2h2: 2 })], quiet: [ex({})] },
  },
  {
    id: 'TX-E-010',
    maturity: 'extended',
    severity: 'warning',
    description: 'Acetylene above 2 ppm.',
    reference: IEC599,
    inputs: ['c2h2'],
    measure: (i) => i.c2h2,
    threshold: { value: 2, unit: 'ppm', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Acetylene watch: monthly sampling.',
    examples: { fires: [ex({ c2h2: 3 })], quiet: [ex({ c2h2: 0.5 })] },
  },
  {
    id: 'TX-E-011',
    maturity: 'extended',
    severity: 'critical',
    description: 'Acetylene rising faster than 1 ppm per month.',
    reference: IEC599,
    inputs: ['c2h2Rate', 'c2h2'],
    measure: (i) => i.c2h2Rate,
    threshold: { value: 1, unit: 'ppm per month', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Active fault suspected: restrict loading and plan an outage for investigation.',
    examples: { fires: [ex({ c2h2Rate: 1.5 })], quiet: [ex({ c2h2Rate: 0.1 })] },
  },
  {
    id: 'TX-E-012',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Hydrogen above 150 ppm.',
    reference: IEC599,
    inputs: ['h2'],
    measure: (i) => i.h2,
    threshold: { value: 150, unit: 'ppm', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Partial discharge watch.',
    examples: { fires: [ex({ h2: 200 })], quiet: [ex({ h2: 40 })] },
  },
  {
    id: 'TX-E-013',
    maturity: 'extended',
    severity: 'warning',
    description: 'Hydrogen rising faster than 10 ppm per month.',
    reference: IEC599,
    inputs: ['h2Rate'],
    measure: (i) => i.h2Rate,
    threshold: { value: 10, unit: 'ppm per month', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Sampling frequency increased.',
    examples: { fires: [ex({ h2Rate: 15 })], quiet: [ex({ h2Rate: 2 })] },
  },
  {
    id: 'TX-E-014',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Ethylene above 60 ppm.',
    reference: IEC599,
    inputs: ['c2h4'],
    measure: (i) => i.c2h4,
    threshold: { value: 60, unit: 'ppm', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Thermal fault watch.',
    examples: { fires: [ex({ c2h4: 80 })], quiet: [ex({ c2h4: 20 })] },
  },
  {
    id: 'TX-E-015',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Carbon dioxide to carbon monoxide ratio below 3: paper degradation suspected.',
    reference: IEC599,
    inputs: ['co2', 'co'],
    measure: (i) => i.co2 / Math.max(1, i.co),
    threshold: { value: 3, unit: 'ratio', source: 'Public', op: '<' },
    action: 'publish',
    outcome: 'Furan analysis requested.',
    examples: { fires: [ex({ co2: 1500, co: 700 })], quiet: [ex({ co2: 3000, co: 300 })] },
  },
  {
    id: 'TX-E-016',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Carbon monoxide above 900 ppm.',
    reference: IEC599,
    inputs: ['co'],
    measure: (i) => i.co,
    threshold: { value: 900, unit: 'ppm', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Cellulose overheating watch.',
    examples: { fires: [ex({ co: 1000 })], quiet: [ex({ co: 300 })] },
  },
  {
    id: 'TX-E-017',
    maturity: 'extended',
    severity: 'warning',
    description: 'Gas trend present with the unit above 90% load: reduce stress while investigating.',
    inputs: ['c2h2Rate', 'h2Rate', 'loading'],
    measure: (i) => (i.c2h2Rate > 0.5 || i.h2Rate > 10 ? i.loading * 100 : 0),
    threshold: { value: 90, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Load cap at 80% recommended pending oil results.',
    examples: { fires: [ex({ c2h2Rate: 0.8, loading: 0.95 })], quiet: [ex({ c2h2Rate: 0.8, loading: 0.6 })] },
  },
  // ------------------------------------------------------------------ extended: insulation, tap changer, bushings
  {
    id: 'TX-E-018',
    maturity: 'extended',
    severity: 'warning',
    description: 'Moisture in oil above 25 ppm.',
    reference: 'IEC 60422 (oil condition, indicative)',
    inputs: ['moisturePpm'],
    measure: (i) => i.moisturePpm,
    threshold: { value: 25, unit: 'ppm', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Oil processing planned.',
    examples: { fires: [ex({ moisturePpm: 30 })], quiet: [ex({ moisturePpm: 10 })] },
  },
  {
    id: 'TX-E-019',
    maturity: 'extended',
    severity: 'critical',
    description: 'Wet oil and a hot spot above 100 °C: bubbling risk.',
    inputs: ['moisturePpm', 'hotSpotC'],
    measure: (i) => (i.moisturePpm > 25 ? i.hotSpotC : 0),
    threshold: { value: 100, unit: '°C', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Load reduction recommended until the oil is dried.',
    examples: { fires: [ex({ moisturePpm: 30, hotSpotC: 110 })], quiet: [ex({ moisturePpm: 10, hotSpotC: 110 })] },
  },
  {
    id: 'TX-E-020',
    maturity: 'extended',
    severity: 'advisory',
    description: 'More than 40 tap changes in 24 hours.',
    inputs: ['tapOps24h'],
    measure: (i) => i.tapOps24h,
    threshold: { value: 40, unit: 'operations', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Voltage control settings review suggested.',
    examples: { fires: [ex({ tapOps24h: 55 })], quiet: [ex({ tapOps24h: 12 })] },
  },
  {
    id: 'TX-E-021',
    maturity: 'extended',
    severity: 'warning',
    description: 'Tap changer beyond 100,000 operations since its last service.',
    inputs: ['tapOpsSinceService'],
    measure: (i) => i.tapOpsSinceService,
    threshold: { value: 100_000, unit: 'operations', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Tap changer service scheduled.',
    examples: { fires: [ex({ tapOpsSinceService: 120_000 })], quiet: [ex({ tapOpsSinceService: 30_000 })] },
  },
  {
    id: 'TX-E-022',
    maturity: 'extended',
    severity: 'warning',
    description: 'Bushing dissipation factor (tan delta) above 0.7%.',
    reference: 'IEC 60137 bushings (indicative)',
    inputs: ['bushingTanDeltaPct'],
    measure: (i) => i.bushingTanDeltaPct,
    threshold: { value: 0.7, unit: '%', source: 'Public', op: '>' },
    action: 'publish',
    outcome: 'Bushing test at next outage.',
    examples: { fires: [ex({ bushingTanDeltaPct: 0.9 })], quiet: [ex({ bushingTanDeltaPct: 0.4 })] },
  },
  {
    id: 'TX-E-023',
    maturity: 'extended',
    severity: 'critical',
    description: 'Bushing capacitance changed by more than 5%: possible layer breakdown.',
    inputs: ['bushingCapChangePct'],
    measure: (i) => i.bushingCapChangePct,
    threshold: { value: 5, unit: '%', source: 'Assumption', op: '>' },
    action: 'recommend',
    outcome: 'Unit to be removed from service for bushing replacement.',
    examples: { fires: [ex({ bushingCapChangePct: 7 })], quiet: [ex({ bushingCapChangePct: 1 })] },
  },
  {
    id: 'TX-E-024',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Unit older than 40 years.',
    inputs: ['ageYears'],
    measure: (i) => i.ageYears,
    threshold: { value: 40, unit: 'years', source: 'Synthetic', op: '>' },
    action: 'publish',
    outcome: 'Included in replacement planning.',
    examples: { fires: [ex({ ageYears: 45 })], quiet: [ex({ ageYears: 20 })] },
  },
  {
    id: 'TX-E-025',
    maturity: 'extended',
    severity: 'warning',
    description: 'Unit older than 40 years with an ageing rate above 1.',
    inputs: ['ageYears', 'ageingRate'],
    measure: (i) => (i.ageYears > 40 ? i.ageingRate : 0),
    threshold: { value: 1, unit: 'x', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Loading caution for an older unit.',
    examples: { fires: [ex({ ageYears: 45, ageingRate: 1.5 })], quiet: [ex({ ageYears: 45, ageingRate: 0.4 })] },
  },
  {
    id: 'TX-E-026',
    maturity: 'extended',
    severity: 'info',
    description: 'Telemetry stale: last known values held.',
    inputs: ['stale'],
    measure: (i) => (i.stale ? 1 : 0),
    threshold: { value: 1, unit: '', source: 'Synthetic', op: '>=' },
    action: 'localSafeMode',
    outcome: 'Local overload protection relied on; coordinator confidence reduced.',
    examples: { fires: [ex({ stale: true })], quiet: [ex({})] },
  },
  {
    id: 'TX-E-027',
    maturity: 'extended',
    severity: 'warning',
    description: 'Oil level below 85% and falling in cold weather: possible leak masked by contraction.',
    inputs: ['oilLevelPct', 'ambientC'],
    measure: (i) => (i.ambientC < 5 ? i.oilLevelPct : 100),
    threshold: { value: 85, unit: '%', source: 'Assumption', op: '<' },
    action: 'publish',
    outcome: 'Inspection requested.',
    examples: { fires: [ex({ oilLevelPct: 82, ambientC: 2 })], quiet: [ex({ oilLevelPct: 82, ambientC: 15 })] },
  },
  {
    id: 'TX-E-028',
    maturity: 'extended',
    severity: 'advisory',
    description: 'Top oil more than 50 °C above ambient at less than 60% load: cooling efficiency degraded.',
    inputs: ['topOilC', 'ambientC', 'loading'],
    measure: (i) => (i.loading < 0.6 ? i.topOilC - i.ambientC : 0),
    threshold: { value: 50, unit: '°C rise', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Radiator and fan inspection requested.',
    examples: { fires: [ex({ topOilC: 70, ambientC: 12, loading: 0.5 })], quiet: [ex({ topOilC: 40, ambientC: 12, loading: 0.5 })] },
  },
  {
    id: 'TX-E-029',
    maturity: 'extended',
    severity: 'warning',
    description: 'Two or more gas indicators abnormal at once (hydrogen, acetylene, ethylene).',
    reference: IEC599,
    inputs: ['h2', 'c2h2', 'c2h4'],
    measure: (i) => (i.h2 > 150 ? 1 : 0) + (i.c2h2 > 2 ? 1 : 0) + (i.c2h4 > 60 ? 1 : 0),
    threshold: { value: 2, unit: 'indicators', source: 'Assumption', op: '>=' },
    action: 'recommend',
    outcome: 'Expert review of the gas record recommended.',
    examples: { fires: [ex({ h2: 200, c2h2: 4 })], quiet: [ex({ h2: 200 })] },
  },
  {
    id: 'TX-E-030',
    maturity: 'extended',
    severity: 'info',
    description: 'Transformer group loaded above 80%.',
    inputs: ['loading'],
    measure: (i) => i.loading * 100,
    threshold: { value: 80, unit: '%', source: 'Assumption', op: '>' },
    action: 'publish',
    outcome: 'Peak loading published for the coordinator.',
    examples: { fires: [ex({ loading: 0.85 })], quiet: [ex({ loading: 0.5 })] },
  },
]);
