/**
 * Generates docs/milestones/M2-divergence.md: for every scenario, what the prototype (parity
 * preset) does and what the engineering preset does, with the reason for each difference.
 * Run: node tools/divergence.ts
 */
import { writeFileSync } from 'node:fs';
import { Engine } from '../src/sim/engine.ts';
import { SCENARIOS, type ScenarioId } from '../src/sim/scenarios.ts';

const WHY: Record<ScenarioId, string> = {
  ie_estate: 'Same balance. The connection is on 220 kV section B.',
  ni_estate: 'Same settled balance. The transfer ramps in at 15 MW/min instead of stepping.',
  ind_exp: 'Same balance.',
  add_solar: 'Solar follows the sun and cloud: about 70 MW at noon in March with broken cloud, rather than a fixed 135 MW.',
  add_bess: 'Same balance (battery idle). Energy-based state of charge with 88% round-trip efficiency.',
  add_gas: 'Same balance (unit idle). When dispatched it now takes 15 minutes to reach full output.',
  wind_up: 'Same settled balance. The wind rises over 20 minutes through the power curve.',
  wind_dn: 'Same settled balance. The wind falls over 20 minutes.',
  sun_set: 'The clock runs forward to sunset and solar fades with the sun, rather than being set to zero.',
  imp_n: 'Same settled balance. The request takes about 10 minutes to take effect.',
  exp_s: 'Same settled balance, ramped.',
  nbr_off: 'Same balance.',
  peak: 'Same settled balance, ramped over 30 minutes. The contingency screen now flags N-1 insecurity.',
  split: 'Same balance. Frequency is now a two-area model: Northern Ireland falls and Ireland rises, then reserves restore both. The prototype moved a single station frequency.',
  n1: 'Same balance (T2 at 124%). The prototype trips T2 within seconds on its 93 °C rule and blacks out the station. With IEC 60076-7, T2 settles just inside 120 °C and stays in service.',
  busfault: 'The prototype loses the whole 220 kV and 110 kV yard. With a sectionalised busbar only section B is lost; section A stays in service.',
  cool_fail: 'The prototype adds 26 °C to T1\'s target and reaches an emergency within seconds. Here the oil pumps fail, T1 alarms on winding temperature after about an hour, and settles near 116 °C.',
  storm: 'The prototype trips T2 six wall seconds later. Here lightning trips T2 at +40 minutes, the wind farm cuts out on high wind at about +2 hours, and T1 then overloads unless someone acts.',
  reset: 'Same baseline.',
};

const pct = (v: number) => `${(v * 100).toFixed(0)}%`;
const rows: string[] = [];
for (const sc of SCENARIOS) {
  const p = new Engine({ preset: 'parity' });
  p.command({ type: 'scenario', id: sc.id });
  const pNow = `${p.s.results.gridFlow.toFixed(0)} MW, T1 ${pct(p.s.C.T1.loadPU)}, T2 ${pct(p.s.C.T2.loadPU)}`;
  for (let i = 0; i < 400; i++) p.step(0.05); // 20 wall seconds, about 40 simulated minutes at 1 s = 2 min
  const pTrips = (['T1', 'T2', 'T3'] as const).filter((id) => p.s.C[id].tripped).join(', ') || 'none';
  const pAfter = `${p.s.sys.mode.toLowerCase()}, trips: ${pTrips}, T1 ${p.s.C.T1.temp.toFixed(0)} °C, T2 ${p.s.C.T2.temp.toFixed(0)} °C`;

  const e = new Engine();
  const r = e.command({ type: 'scenario', id: sc.id });
  const g = r.deltas.find((d) => d.key === 'grid');
  const imp = g ? g.after : e.s.results.gridFlow;
  const t1 = r.deltas.find((d) => d.key === 't1');
  const t2 = r.deltas.find((d) => d.key === 't2');
  const eNow = `${imp.toFixed(0)} MW, T1 ${(t1 ? t1.after : e.s.C.T1.loadPU * 100).toFixed(0)}%, T2 ${(t2 ? t2.after : e.s.C.T2.loadPU * 100).toFixed(0)}%${r.settling ? ' (settled)' : ''}`;
  e.advance(2 * 3600);
  const eTrips = (['T1', 'T2', 'T3', 'T4'] as const).filter((id) => e.s.C[id].tripped).join(', ') || 'none';
  const eAfter = `${e.s.condition.toLowerCase()}, trips: ${eTrips}, T1 ${e.s.C.T1.temp.toFixed(0)} °C, T2 ${e.s.C.T2.temp.toFixed(0)} °C`;
  rows.push(`| ${sc.title} | ${pNow} | ${pAfter} | ${eNow} | ${eAfter} | ${WHY[sc.id]} |`);
}

const md = `# Milestone 2: prototype versus engineering preset, per scenario

Generated by \`node tools/divergence.ts\` from both engines. Each scenario is applied to the baseline.

- **Prototype** columns come from the parity preset, which reproduces the original prototype exactly (proved by \`tests/parity\`). "After" is 20 prototype seconds later, about 40 simulated minutes at 1 s = 2 min.
- **Engineering** columns come from the preset the demo runs. "Applied" shows the settled state where a change ramps in. "After" is two simulated hours later.

| Scenario | Prototype: applied | Prototype: after | Engineering: applied | Engineering: after 2 h | Why they differ |
|---|---|---|---|---|---|
${rows.join('\n')}
`;
writeFileSync(new URL('../docs/milestones/M2-divergence.md', import.meta.url), md);
console.log(md);
