/** Generates docs/METHOD.md from the assumptions table, so the document can never drift from the code. */
import { writeFileSync } from 'node:fs';
import { assumptionTable } from '../src/config/assumptions.ts';

const rows = assumptionTable();
const groups = [...new Set(rows.map((r) => r.group))];
const esc = (s: string) => s.replace(/\|/g, '\\|');
const body = groups.map((g) => {
  const rs = rows.filter((r) => r.group === g);
  if (g === 'Simplifications') return `## ${g}\n\n${rs.map((r) => `- **${r.label}.** ${r.value}`).join('\n')}`;
  return `## ${g}\n\n| Item | Value | Source | Reference and note |\n|---|---|---|---|\n${rs.map((r) => `| ${esc(r.label)} | ${esc(`${r.value} ${r.unit}`.trim())} | ${r.source} | ${esc([r.ref, r.note].filter(Boolean).join('. '))} |`).join('\n')}`;
}).join('\n\n');

const md = `# Method and assumptions

Generated by \`node tools/method.ts\` from \`src/config/assumptions.ts\`, the single source of truth. The in-app Method and assumptions panel reads the same table.

Source types: **Typical value** (a recognised typical figure, with its reference), **Assumption** (chosen for this fictional station), **Simplification** (something the model deliberately does not do).

## How the simulation works

- **Balance.** Energisation follows the topology. Each busbar balances exactly: the 400 kV infeed makes up the difference within its limits. T1 and T2 share by impedance (equally, being identical). With the 220 kV bus-section breaker open, each section balances through its own unit. Flow directions come from the sign of each solved flow.
- **Transformers.** IEC 60076-7 exponential model for top-oil and winding hot-spot, with cooling stages switched on winding temperature, forced cooling, oil-pump failure, ambient temperature from the time of day, and relative ageing.
- **Protection.** Winding and oil temperature alarms and trips, backup overcurrent set above maximum overload, differential and bus-zone protection, with lockout until a person confirms the cause is cleared. Disconnectors and earth switches are interlocked.
- **Plant.** Wind power curve with soft high-wind cut-out and restart hysteresis; solar from sun position and cloud; battery energy with round-trip efficiency; gas start-up, minimum stable generation and ramp; transfer requests that take effect over about 10 minutes.
- **Frequency.** Two areas (Ireland and Northern Ireland) coupled while the island is whole. The displayed value is quasi-steady on the simulation clock; each sudden step also produces a real-time transient (swing equation with damping and primary response) reported with its rate of change and nadir.
- **Time.** A fixed 5-second simulation step. The clock compression is always visible. The engine is deterministic and every state can be rebuilt from its input log.

${body}
`;
writeFileSync(new URL('../docs/METHOD.md', import.meta.url), md);
console.log(`wrote docs/METHOD.md (${rows.length} rows)`);
